# Generated by Django 5.2.17 on 2026-09-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('autor', models.CharField(max_length=150)),
                ('genero', models.CharField(max_length=80)),
                ('lido', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['nome', 'id'],
            },
        ),
    ]
